In [2]:
import torch
var = torch.tensor([[101, 7592, 2088, 102, 0, 0, 0, 0],
                         [101, 7592, 15756, 2897, 2005, 17953, 2361, 102]])
var.size()

var.reshape(-1,1)
var

tensor([[  101,  7592,  2088,   102,     0,     0,     0,     0],
        [  101,  7592, 15756,  2897,  2005, 17953,  2361,   102]])

In [7]:
n = torch.randn(2,3,4)
print(n)
print(n.size())

nn = n.permute(2,1,0)
print(nn)
print(nn.size())

nn.reshape(4,2,-1)
nn

tensor([[[ 0.1643,  1.7894,  1.1904,  0.3750],
         [ 0.4909,  1.1635, -2.1646,  2.3660],
         [ 0.2020,  0.1235,  1.1499,  1.2718]],

        [[-0.9511, -0.9324,  0.9465,  1.1656],
         [-0.0150, -0.2678, -0.2961,  2.0758],
         [-1.1055,  0.7486,  1.5985, -1.3079]]])
torch.Size([2, 3, 4])
tensor([[[ 0.1643, -0.9511],
         [ 0.4909, -0.0150],
         [ 0.2020, -1.1055]],

        [[ 1.7894, -0.9324],
         [ 1.1635, -0.2678],
         [ 0.1235,  0.7486]],

        [[ 1.1904,  0.9465],
         [-2.1646, -0.2961],
         [ 1.1499,  1.5985]],

        [[ 0.3750,  1.1656],
         [ 2.3660,  2.0758],
         [ 1.2718, -1.3079]]])
torch.Size([4, 3, 2])


tensor([[[ 0.1643, -0.9511],
         [ 0.4909, -0.0150],
         [ 0.2020, -1.1055]],

        [[ 1.7894, -0.9324],
         [ 1.1635, -0.2678],
         [ 0.1235,  0.7486]],

        [[ 1.1904,  0.9465],
         [-2.1646, -0.2961],
         [ 1.1499,  1.5985]],

        [[ 0.3750,  1.1656],
         [ 2.3660,  2.0758],
         [ 1.2718, -1.3079]]])

In [21]:
a = tuple(torch.randn(2,3,2,4))
print("a=", a)
print(a.__sizeof__())
s = torch.stack(a)[:,:,0]
print("s=",s)
print(s.__sizeof__())

a= (tensor([[[ 0.6094,  0.9228,  1.1185, -1.9062],
         [-1.1136,  1.2768,  1.3932, -1.0727]],

        [[ 0.7710, -0.6064,  0.0208,  0.3414],
         [-1.0594, -0.9006, -1.2622,  0.4067]],

        [[ 0.1168,  0.1304, -0.8386,  0.2288],
         [ 0.3927,  0.3871, -1.0883, -0.6066]]]), tensor([[[-0.7158,  1.0344,  0.3684, -1.1967],
         [-0.5031,  0.4174,  0.4012, -1.3028]],

        [[-1.5571,  1.5550, -1.7356,  0.2444],
         [-2.3835,  0.4826,  0.3088, -0.3048]],

        [[-1.2546, -0.1764, -0.4617,  1.0321],
         [ 0.8912, -1.0147, -1.3106, -2.4852]]]))
40
s= tensor([[[ 0.6094,  0.9228,  1.1185, -1.9062],
         [ 0.7710, -0.6064,  0.0208,  0.3414],
         [ 0.1168,  0.1304, -0.8386,  0.2288]],

        [[-0.7158,  1.0344,  0.3684, -1.1967],
         [-1.5571,  1.5550, -1.7356,  0.2444],
         [-1.2546, -0.1764, -0.4617,  1.0321]]])
56


In [24]:
ss = s.permute(1,0,2)
print(ss)
print("\n")
print(torch.mean(ss,1))

tensor([[[ 0.6094,  0.9228,  1.1185, -1.9062],
         [-0.7158,  1.0344,  0.3684, -1.1967]],

        [[ 0.7710, -0.6064,  0.0208,  0.3414],
         [-1.5571,  1.5550, -1.7356,  0.2444]],

        [[ 0.1168,  0.1304, -0.8386,  0.2288],
         [-1.2546, -0.1764, -0.4617,  1.0321]]])


tensor([[-0.0532,  0.9786,  0.7434, -1.5514],
        [-0.3930,  0.4743, -0.8574,  0.2929],
        [-0.5689, -0.0230, -0.6501,  0.6305]])
